# site properties and page defaults
title: Frank Fan's Website Template
subtitle: Research Assistant Professor, Department of Human Genetics
subsubtitle: School of Public Health, University of Pittsburgh
description: School of Public Health, University of Pittsburgh
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: frank.fan@pitt.edu
  orcid: 0000-0003-0121-3959
  google-scholar: ZLBQ0xkAAAAJ
  github: https://github.com/KH-Fan
  research gate: https://www.researchgate.net/profile/Kang-Hsien-Fan

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
